# Generated by Django 2.2.2 on 2019-06-26 15:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0004_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='roads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceid', models.CharField(max_length=50)),
                ('exs', models.FloatField()),
                ('notes', models.CharField(max_length=254)),
                ('roadid', models.CharField(max_length=50)),
                ('onme', models.CharField(max_length=200)),
                ('rtenme', models.CharField(max_length=200)),
                ('ntlclass', models.CharField(max_length=200)),
                ('fclass', models.FloatField()),
                ('crgway', models.FloatField()),
                ('numlanes', models.FloatField()),
                ('lnewidthm', models.FloatField()),
                ('rdwidthm', models.FloatField()),
                ('axleloadmt', models.FloatField()),
                ('totloadmt', models.FloatField()),
                ('srftpe', models.FloatField()),
                ('srfcond', models.FloatField()),
                ('srfprep', models.FloatField()),
                ('isseasonal', models.FloatField()),
                ('curntprac', models.FloatField()),
                ('gdwthrprac', models.FloatField()),
                ('bdwthrprac', models.FloatField()),
                ('speedlimit', models.FloatField()),
                ('curntspeed', models.FloatField()),
                ('gnralspeed', models.FloatField()),
                ('isundrcstr', models.FloatField()),
                ('cstwrketc', models.DateField()),
                ('graddeg', models.FloatField()),
                ('sec', models.FloatField()),
                ('hasshouldr', models.FloatField()),
                ('hassidewlk', models.FloatField()),
                ('drivside', models.FloatField()),
                ('iselevated', models.FloatField()),
                ('hasmedian', models.FloatField()),
                ('opstatus', models.FloatField()),
                ('length_km', models.FloatField()),
                ('shape_leng', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='Building',
        ),
    ]
