# Generated by Django 2.2.2 on 2019-06-26 20:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0005_auto_20190626_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='rails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid_rail_d', models.IntegerField()),
                ('f_code_des', models.CharField(max_length=254)),
                ('exs_descri', models.CharField(max_length=254)),
                ('fco_descri', models.CharField(max_length=254)),
                ('fid_countr', models.IntegerField()),
                ('iso', models.CharField(max_length=7)),
                ('isocountry', models.CharField(max_length=54)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='roads',
        ),
    ]
