# Generated by Django 2.2.2 on 2019-06-27 05:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_auto_20190626_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='roads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_descri', models.CharField(max_length=254)),
                ('rtt_descri', models.CharField(max_length=254)),
                ('f_code_des', models.CharField(max_length=10)),
                ('iso', models.CharField(max_length=7)),
                ('isocountry', models.CharField(max_length=54)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
