# Generated by Django 2.2.2 on 2019-06-27 07:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0007_roads'),
    ]

    operations = [
        migrations.CreateModel(
            name='water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=7)),
                ('country', models.CharField(max_length=54)),
                ('f_code_des', models.CharField(max_length=254)),
                ('hyc_descri', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
