from __future__ import unicode_literals
from django.db import models as model
from django.contrib.gis.db import models as gis_models
from django.db.models import Manager as GeoManager
from django.contrib.gis.db import models  

# Create your models here.
class Incidence(models.Model):
    title = model.CharField(max_length=20)
    description = model.TextField(max_length=250, null=True    )
    date_reported = model.DateField(auto_now_add=True)
    location = gis_models.PointField(srid=4326)
    objects = GeoManager()
    def __str__(self):
            return self.title
    class Meta:
            verbose_name_plural =" Incidences"
                                                                                             
class County(models.Model):                                                                  
    id_0 = models.BigIntegerField()                                                          
    iso = models.CharField(max_length=3)                                                     
    name_0 = models.CharField(max_length=75)                                                 
    objectid_1 = models.BigIntegerField()                                                    
    iso3 = models.CharField(max_length=5)                                                    
    name_engli = models.CharField(max_length=50)                                             
    name_iso = models.CharField(max_length=54)                                               
    name_fao = models.CharField(max_length=50)                                               
    name_local = models.CharField(max_length=54)                                             
    name_obsol = models.CharField(max_length=150)                                            
    name_varia = models.CharField(max_length=160)                                            
    name_nonla = models.CharField(max_length=50)                                             
    name_frenc = models.CharField(max_length=50)                                             
    name_spani = models.CharField(max_length=50)                                             
    name_russi = models.CharField(max_length=50)                                             
    name_arabi = models.CharField(max_length=50)                                             
    name_chine = models.CharField(max_length=50)                                             
    waspartof = models.CharField(max_length=100)                                             
    contains = models.CharField(max_length=50)                                               
    sovereign = models.CharField(max_length=40)
    iso2 = models.CharField(max_length=4)
    www = models.CharField(max_length=2)
    fips = models.CharField(max_length=6)
    ison = models.FloatField()
    validfr = models.CharField(max_length=12)
    validto = models.CharField(max_length=10)
    pop2000 = models.FloatField()
    sqkm = models.FloatField()
    popsqkm = models.FloatField()
    unregion1 = models.CharField(max_length=254)
    unregion2 = models.CharField(max_length=254)
    developing = models.FloatField()
    cis = models.FloatField()
    transition = models.FloatField()
    oecd = models.FloatField()
    wbregion = models.CharField(max_length=254)
    wbincome = models.CharField(max_length=254)
    wbdebt = models.CharField(max_length=254)
    wbother = models.CharField(max_length=254)
    ceeac = models.FloatField()
    cemac = models.FloatField()
    ceplg = models.FloatField()
    comesa = models.FloatField()
    eac = models.FloatField()
    ecowas = models.FloatField()
    igad = models.FloatField()
    ioc = models.FloatField()
    mru = models.FloatField()
    sacu = models.FloatField()
    uemoa = models.FloatField()
    uma = models.FloatField()
    palop = models.FloatField()
    parta = models.FloatField()
    cacm = models.FloatField()
    eurasec = models.FloatField()
    agadir = models.FloatField()
    saarc = models.FloatField()
    asean = models.FloatField()
    nafta = models.FloatField()
    gcc = models.FloatField()
    csn = models.FloatField()
    caricom = models.FloatField()
    eu = models.FloatField()
    can = models.FloatField()
    acp = models.FloatField()
    landlocked = models.FloatField()
    aosis = models.FloatField()
    sids = models.FloatField()
    islands = models.FloatField()
    ldc = models.FloatField()
    geom = models.MultiPolygonField(srid=4326)
    
class CountryB(models.Model):
    featurecla = models.CharField(max_length=15)
    scalerank = models.IntegerField()
    labelrank = models.IntegerField()
    sovereignt = models.CharField(max_length=32)
    sov_a3 = models.CharField(max_length=3)
    adm0_dif = models.IntegerField()
    level = models.IntegerField()
    type = models.CharField(max_length=17)
    admin = models.CharField(max_length=35)
    adm0_a3 = models.CharField(max_length=3)
    geou_dif = models.IntegerField()
    geounit = models.CharField(max_length=35)
    gu_a3 = models.CharField(max_length=3)
    su_dif = models.IntegerField()
    subunit = models.CharField(max_length=35)
    su_a3 = models.CharField(max_length=3)
    brk_diff = models.IntegerField()
    name = models.CharField(max_length=25)
    name_long = models.CharField(max_length=35)
    brk_a3 = models.CharField(max_length=3)
    brk_name = models.CharField(max_length=32)
    brk_group = models.CharField(max_length=17)
    abbrev = models.CharField(max_length=13)                                                 
    postal = models.CharField(max_length=4)                                                  
    formal_en = models.CharField(max_length=52)
    formal_fr = models.CharField(max_length=35)
    name_ciawf = models.CharField(max_length=45)
    note_adm0 = models.CharField(max_length=22)
    note_brk = models.CharField(max_length=51)
    name_sort = models.CharField(max_length=35)
    name_alt = models.CharField(max_length=14)
    mapcolor7 = models.IntegerField()
    mapcolor8 = models.IntegerField()
    mapcolor9 = models.IntegerField()
    mapcolor13 = models.IntegerField()
    pop_est = models.BigIntegerField()
    pop_rank = models.IntegerField()
    gdp_md_est = models.FloatField()
    pop_year = models.IntegerField()
    lastcensus = models.IntegerField()
    gdp_year = models.IntegerField()
    economy = models.CharField(max_length=26)
    income_grp = models.CharField(max_length=23)
    wikipedia = models.IntegerField()
    fips_10_field = models.CharField(max_length=3)
    iso_a2 = models.CharField(max_length=3)
    iso_a3 = models.CharField(max_length=3)
    iso_a3_eh = models.CharField(max_length=3)
    iso_n3 = models.CharField(max_length=3)
    un_a3 = models.CharField(max_length=4)
    wb_a2 = models.CharField(max_length=3)
    wb_a3 = models.CharField(max_length=3)
    woe_id = models.IntegerField()
    woe_id_eh = models.IntegerField()
    woe_note = models.CharField(max_length=167)
    adm0_a3_is = models.CharField(max_length=3)
    adm0_a3_us = models.CharField(max_length=3)
    adm0_a3_un = models.IntegerField()
    adm0_a3_wb = models.IntegerField()
    continent = models.CharField(max_length=23)
    region_un = models.CharField(max_length=23)
    subregion = models.CharField(max_length=25)
    region_wb = models.CharField(max_length=26)
    name_len = models.IntegerField()
    long_len = models.IntegerField()
    abbrev_len = models.IntegerField()
    tiny = models.IntegerField()
    homepart = models.IntegerField()
    min_zoom = models.FloatField()
    min_label = models.FloatField()
    max_label = models.FloatField()
    ne_id = models.BigIntegerField()
    wikidataid = models.CharField(max_length=8)
    name_ar = models.CharField(max_length=72)
    name_bn = models.CharField(max_length=125)
    name_de = models.CharField(max_length=46)
    name_en = models.CharField(max_length=44)
    name_es = models.CharField(max_length=44)
    name_fr = models.CharField(max_length=54)
    name_el = models.CharField(max_length=88)
    name_hi = models.CharField(max_length=123)
    name_hu = models.CharField(max_length=41)
    name_id = models.CharField(max_length=46)
    name_it = models.CharField(max_length=44)
    name_ja = models.CharField(max_length=63)
    name_ko = models.CharField(max_length=47)
    name_nl = models.CharField(max_length=46)
    name_pl = models.CharField(max_length=47)
    name_pt = models.CharField(max_length=43)
    name_ru = models.CharField(max_length=86)
    name_sv = models.CharField(max_length=42)
    name_tr = models.CharField(max_length=42)
    name_vi = models.CharField(max_length=56)
    name_zh = models.CharField(max_length=36)
    geom = models.MultiPolygonField(srid=4326)
    


class rails(models.Model):
    fid_rail_d = models.IntegerField()
    f_code_des = models.CharField(max_length=254)
    exs_descri = models.CharField(max_length=254)
    fco_descri = models.CharField(max_length=254)
    fid_countr = models.IntegerField()
    iso = models.CharField(max_length=7)
    isocountry = models.CharField(max_length=54)
    geom = models.MultiLineStringField(srid=4326)
    

class roads(models.Model):
    med_descri = models.CharField(max_length=254)
    rtt_descri = models.CharField(max_length=254)
    f_code_des = models.CharField(max_length=10)
    iso = models.CharField(max_length=7)
    isocountry = models.CharField(max_length=54)
    geom = models.MultiLineStringField(srid=4326)



class water(models.Model):
    iso = models.CharField(max_length=7)
    country = models.CharField(max_length=54)
    f_code_des = models.CharField(max_length=254)
    hyc_descri = models.CharField(max_length=254)
    name = models.CharField(max_length=254)
    geom = models.MultiPolygonField(srid=4326)





